# Setup
title:               Emilio
tagline:             'You can see a lot just by observing'
description:         'You can see a lot just by observing - Yogi Berra'
url:                 https://emialb34i.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Emilio Alberini
  url:               https://emialb34i.github.io
  email:             emilio.alberini@gmail.com

github:
  repo:           https://github.com/emialb34i

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-7H3TTHYKFZ
